platform :ios,'9.0'

target ‘ABigFishTV’ do
pod 'ReactiveCocoa','2.5'
pod 'AFNetworking', '2.5.4'
pod 'Masonry'
pod 'MBProgressHUD','~> 0.9'
pod 'MJExtension'
pod 'SDWebImage','~> 3.7.3'
pod 'MyLayout', '1.4.2'
pod 'MXParallaxHeader'
pod 'JHUD'
pod 'MJRefresh','3.1.9'
pod 'SGQRCode'
pod 'TZImagePickerController'
pod 'AGEmojiKeyboard'
pod 'MWPhotoBrowser','2.1.1'
pod 'FDFullscreenPopGesture','1.1'
pod 'ZFDownload'
pod 'SDCycleScrollView'
pod 'XHLaunchAd','3.9.3'
#pod 'FlyImage'

pod 'UMCCommon'
pod 'UMCSecurityPlugins'
pod 'UMCAnalytics'
pod 'UMCPush'
pod 'UMCErrorCatch'

end
